config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :number_of_guests, :address, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1>All of our flats (<%= @flats.length %>)</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-12 col-md-6">
        <div class="card m-3 bg-light border">
          <img src="https://picsum.photos/id/101/350/200" alt="#" style="object-fit: none;">
          <div class="text pl-3 pt-3">
            <h3><%= flat.name %></h3>
            <p><%= flat.address %></p>
            <div class="d-flex">
              <div class="d-flex mr-2">
                <h4><%= flat.number_of_guests %></h4>
                <i class="fas fa-user-friends"></i>
              </div>
              <div class="d-flex">
                <h4><%= flat.price_per_night %></h4>
                <i class="fas fa-euro-sign"></i>
              </div>
            </div>
          </div>
          <div class="p-2 bg-white d-flex justify-content-around">
            <%= link_to "More info", flat_path(flat), class:"text-primary" %>
            <%= link_to "Edit", flat_path(flat), class:"text-warning" %>
            <%= link_to "Remouve", flat_path(flat), class:"text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for(@flat) do |f| %>

  <%= f.input :name %>

  <%= f.input :address %>

  <%= f.input :description %>

  <%= f.input :price_per_night %>

  <%= f.input :number_of_guests %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
      <div><%= link_to "Home", flats_path, class: "navbar-brand" %></div>
      <div class="" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <%= link_to "Add Flat", new_flat_path, class:"btn btn-outline-primary ml-2 my-2 my-sm-0" %>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>